#pragma once

#include <cstddef>
#include "battleparam.h"

namespace Omnispawn
{
    enum class NewBPIndex
    {
        // Start from the end of vanilla indices
        Mothmant = (size_t) BPIndex::END_INDEX + 1,
        Monest,
        SavageWolf,
        BarbarousWolf,
        PoisonLily,
        NarLily,
        SinowBeat,
        Canadine,
        CanadineRing,
        Canane,
        ChaosSorcerer,
        BeeR,
        BeeL,
        ChaosBringer,
        DarkBelra,
        SinowGold,
        RagRappy,
        AlRappy,
        NanoDragon,
        Dubchic,
        Gillchic,
        Garanz,
        DarkGunner,
        Bulclaw,
        Claw,
        PofuillySlime,
        PanArms,
        Hidoom,
        Migium,
        PouillySlime,
        Dubwitch,
        Hildebear,
        Hildeblue,
        Booma,
        Gobooma,
        Gigobooma,
        GrassAssassin,
        EvilShark,
        PalShark,
        GuilShark,
        Delsaber,
        Dimenian,
        LaDimenian,
        SoDimenian,

        SinowBerill,
        Gee,
        Delbiter,
        SinowSpigell,
        GiGue,
        Epsilon,
        Epsigard,
        IllGill,
        Deldepth,
        Mericarol,
        UlGibbon,
        ZolGibbon,
        Gibbles,
        Morfos,
        Recobox,
        Recon,
        SinowZoa,
        SinowZele,
        Merikle,
        Mericus,
        Merillia,
        Meriltas,
        Dolmolm,
        Dolmdarl,

        Boota,
        ZeBoota,
        BaBoota,
        ZuCrater,
        PazuzuCrater,
        ZuDesert,
        PazuzuDesert,
        Astark,
        SatelliteLizardCrater,
        SatelliteLizardDesert,
        YowieCrater,
        YowieDesert,
        Dorphon,
        DorphonEclair,
        Goran,
        PyroGoran,
        GoranDetonator,
        MerissaA,
        MerissaAA,
        Girtablulu,

        EP1_START_INDEX = Mothmant,
        EP1_END_INDEX = SoDimenian,

        EP2_START_INDEX = SinowBerill,
        EP2_END_INDEX = Dolmdarl,

        EP4_START_INDEX = Boota,
        EP4_END_INDEX = Girtablulu
    };

    void ApplyOmnispawnPatch();
};
